shouldInstrument: true
configRefreshInterval: 15
traceFileLocation: C:\\Users\\ashut\\Documents\\Personal Projects\\manualTesting
agentRules:
  - ClassA::getAr@ENTRY::STACK
  - ClassA::getAr@ENTRY::ARGS
  - ClassA::getAr@EXIT::RET
  - ClassA::getA@ENTRY::ARGS
  - ClassA::getA@ENTRY::STACK
  - ClassA::getA@EXIT::STACK
  - ClassA::getA@EXIT::RET
  - ClassB::delayed@PROFILE
  - ClassB::delayed@ENTRY::HEAP
  - ClassB::delayed@ENTRY::ADD::[System.out.println(20);]
  - ClassA::getAr@ENTRY::ADD::[System.out.println(this.getClass().getName());]
  - ClassA::getA@AT(11)::ADD::[System.out.println(499);]
  - ClassA::getA@AT(11)::ADD::[System.out.println(499 + "," + "Ashutosh");]
printClassLoaderTrace: true
printJVMSystemProperties: true
printEnvironmentVariables: true
printJVMHeapUsage: true
maxHeapDumps: 3